### PR TITLE
Removal of all content from zanata-assets repo

### PR DESCRIPTION
**Pull request by ghost**
https://zanata.atlassian.net/browse/ZNTA-2041

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-assets/15)

### CODE REVIEW

**Review by alex-sl-eng — APPROVED** [review]

**Comment by aeng** [comment]
Reviewed 1951 of 1951 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-assets/15)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-assets/15#-:-KqZvLYrnNWAi3x0if6j:bnfp4nl)*

**Comment by kathryngo** [comment]
thanks @aeng 
Does this need QA? 
I will create a label for On QA if it does

**Comment by aeng** [comment]
Not required. you can merge this in.

**Pull request merged**
